// White-label brand config — North Canyon Medical Center
// Generated by the Worker-Bee white-label builder for northcanyon.org

import type { ThemeId } from './themes'

export interface Brand {
  name: string
  tagline: string
  company: string
  logoPath: string
  logoAlt: string
  defaultTheme: ThemeId
  accentColor: string
  contactEmail: string
  website: string
  industry: string
}

const brand: Brand = {
  name:         'NCMC Training',
  tagline:      'North Canyon Medical Center — Staff Compliance Training',
  company:      'North Canyon Medical Center',
  logoPath:     '/ncmc-logo.svg',
  logoAlt:      'North Canyon Medical Center',
  defaultTheme: 'arctic',
  accentColor:  '#1a56a0',
  contactEmail: 'hr@northcanyon.org',
  website:      'https://northcanyon.org',
  industry:     'healthcare',
}

export default brand
