// White-label brand config — edit this file to rebrand the LMS
// Generated by the Worker-Bee white-label builder from vericorecg.com

import type { ThemeId } from './themes'

export interface Brand {
  name: string           // Platform name shown in nav
  tagline: string        // Subtitle on login card
  company: string        // Full legal/display company name
  logoPath: string       // Path under /public or full URL
  logoAlt: string
  defaultTheme: ThemeId  // Theme applied before user picks one
  accentColor: string    // Matches --accent for raw CSS contexts
  contactEmail: string
  website: string
  industry: string       // Used for compliance module selection
}

const brand: Brand = {
  name:         'Vericore LMS',
  tagline:      'Blockchain Compliance Training — built for projects that can\'t afford to get it wrong.',
  company:      'Vericore Compliance Group',
  logoPath:     '/vericore-logo.svg',
  logoAlt:      'Vericore Compliance Group',
  defaultTheme: 'vericore',
  accentColor:  '#00e5a0',
  contactEmail: 'hello@vericorecg.com',
  website:      'https://www.vericorecg.com',
  industry:     'blockchain-crypto',
}

export default brand
